version: "3.8"
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ABC123
      MYSQL_DATABASE: gains_demo
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    depends_on:
      - db
    environment:
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: "mysql+mysqlconnector://root:ABC123@db/gains_demo"
    ports:
      - "5000:5000"
    volumes:
      - .:/app

volumes:
  db_data: